# Use `pre-commit install` when this file is updated.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: ^src/
        args: [--strict]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        language_version: python3
        args:
          - --max-line-length=120
          - --ignored-modules=turtle,tkinter
          - --disable=invalid-name,too-many-arguments,too-many-locals,global-statement,too-many-lines,too-many-branches,too-many-statements,import-error,fixme

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3
